# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d6f18bd72e25a8ee85b1c6668d9b007ba6e0885eb98e01a8387cc6d2809ae05dadb2b062bc8753e02d5e36a7433a9f8569ec854ed506ee1ba06b6c2b7996d5

test:
  secret_key_base: 34740e2bb5cdd6cb453962cbfebd9afa05fa308337f3234d03de20c67e2e26e2fc8016b416164fe5034be1d081f7925ac3bfdff580c2777a767325038fe71b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
